In [2]:
library(ggplot2)
library(reshape2)

In [99]:
data <- read.table('/home/hdickie/sandbox/results.csv',sep=',',stringsAsFactors=FALSE,header=TRUE)

#data$Credit.1 <- 20000 - data$Credit.1 #flipping these y axis so the plot isnt as sparse
#data$Credit.1.Grace.Period.Balance <- 20000 - data$Credit.1.Grace.Period.Balance

melted.data <- melt(data)

title_text=paste("Expense Forecast:",min(data$Date),'->',max(data$Date),collapse=' ')
subtitle_text=paste("Generated",Sys.time(),collapse=' ')

png('/home/hdickie/sandbox/results.png',width=1800,height=1000)

ggplot(melted.data,aes(x=Date,y=value,group=variable,color=variable)) + geom_line(size=2) + theme(plot.subtitle = element_text(hjust = 0.5,size=20), legend.title=element_text(size=14,face="bold"),axis.title=element_text(size=18,face="bold"), plot.title = element_text(hjust = 0.5,size=30),axis.text.y = element_text(size=18),axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,size=18),legend.text=element_text(size=18)) + labs(title = title_text, subtitle = subtitle_text) 

dev.off()

Using Date, Memo as id variables

png
  2

In [98]:
data

   Date       Checking Savings Credit.1 Credit.1.Grace.Period.Balance Loan.A
1  2022-06-06  298.48  50      2434.88  1832.54                       4746.180
2  2022-06-07  298.48  50      2434.88  1832.54                       4746.180
3  2022-06-08  298.48  50      2434.88  1862.54                       4746.180
4  2022-06-09  298.48  50      2434.88  1892.54                       4746.180
5  2022-06-10  298.48  50      2434.88  1922.54                       4746.180
6  2022-06-11  298.48  50      2434.88  1952.54                       4746.180
7  2022-06-12  298.48  50      2434.88  2082.54                       4746.180
8  2022-06-13  298.48  50      2434.88  2112.54                       4746.180
9  2022-06-14  298.48  50      2434.88  2142.54                       4746.180
10 2022-06-15  298.48  50      2434.88  2172.54                       4746.180
11 2022-06-16  298.48  50      2434.88  2272.54                       4746.180
12 2022-06-17  298.48  50      2434.88  2302.54                       4746.180
13 2022-06-18 2498.48  50      2434.88  2332.54                       4746.180
14 2022-06-19 2498.48  50      2434.88  2369.54                       4746.180
15 2022-06-20 2498.48  50      2434.88  2399.54                       4746.180
16 2022-06-21 2498.48  50      2434.88  2429.54                       4746.180
17 2022-06-22 2498.48  50      2434.88  2459.54                       4746.180
18 2022-06-23 2498.48  50      2434.88  2489.54                       4746.180
19 2022-06-24 2498.48  50      2434.88  2519.54                       4746.180
20 2022-06-25 2498.48  50      2434.88  2549.54                       4746.180
21 2022-06-26 2498.48  50      2434.88  2579.54                       4746.180
22 2022-06-27 2498.48  50      2434.88  2609.54                       4746.180
23 2022-06-28 2498.48  50      2434.88  2639.54                       4746.180
24 2022-06-29 2498.48  50      2434.88  2669.54                       4746.180
25 2022-06-30 2498.48  50      2434.88  2699.54                       4746.180
26 2022-07-01  498.48  50      2434.88  2729.54                       4746.180
27 2022-07-02 2698.48  50      2434.88  2759.54                       4746.180
28 2022-07-03 2475.28  50      2434.88  2789.54                       4716.034
29 2022-07-04 2475.28  50      2434.88  2819.54                       4716.034
30 2022-07-05 2475.28  50      2434.88  2849.54                       4716.034
⋮  ⋮          ⋮        ⋮       ⋮        ⋮                             ⋮
61 2022-08-05 4612.08  50      5352.590 1047                          4688.565
62 2022-08-06 4612.08  50      5352.590 1077                          4688.565
63 2022-08-07 4572.08  50      6495.482   30                          4688.565
64 2022-08-08 4572.08  50      6495.482   60                          4688.565
65 2022-08-09 4572.08  50      6495.482   90                          4688.565
66 2022-08-10 4572.08  50      6495.482  120                          4688.565
67 2022-08-11 4572.08  50      6495.482  150                          4688.565
68 2022-08-12 4572.08  50      6495.482  280                          4688.565
69 2022-08-13 6772.08  50      6495.482  310                          4688.565
70 2022-08-14 6772.08  50      6495.482  340                          4688.565
71 2022-08-15 6772.08  50      6495.482  370                          4688.565
72 2022-08-16 6772.08  50      6495.482  470                          4688.565
73 2022-08-17 6772.08  50      6495.482  500                          4688.565
74 2022-08-18 6772.08  50      6495.482  530                          4688.565
75 2022-08-19 6772.08  50      6495.482  567                          4688.565
76 2022-08-20 6772.08  50      6495.482  597                          4688.565
77 2022-08-21 6772.08  50      6495.482  627                          4688.565
78 2022-08-22 6772.08  50      6495.482  657                          4688.565
79 2022-08-23 6772.08  50      6495.482  687                          4688.565
80 2022-08-24 6772.08  50      6495.482  717                          4688.565
81 2022-08-25 6772.08  50      6495.482  747                          4688.565
82 2022-08-26 6772.08  50      6495.482  777                          4688.565
83 2022-08-27 6772.08  50      6495.482  807                          4688.565
84 2022-08-28 6772.08  50      6495.482  837                          4688.565
85 2022-08-29 6772.08  50      6495.482  867                          4688.565
86 2022-08-30 6772.08  50      6495.482  897                          4688.565
87 2022-08-31 6772.08  50      6495.482  927                          4688.565
88 2022-09-01 4772.08  50      6495.482  957                          4688.565
89 2022-09-02 4772.08  50      6495.482  987                          4688.565
90 2022-09-03 4548.88  50      6495.482 1017                          4660.997
   Loan.A.Interest Loan.B   Loan.B.Interest Loan.C   Loan.C.Interest Loan.D
1   0.0000000      1919.550 0.0000000       4726.680  0.0000000      1823.31
2   0.0000000      1919.550 0.0000000       4726.680  0.0000000      1823.31
3   0.5574569      1919.550 0.2254584       4726.680  0.4865795      1823.31
4   1.1149137      1919.550 0.4509169       4726.680  0.9731590      1823.31
5   1.6723706      1919.550 0.6763753       4726.680  1.4597385      1823.31
6   2.2298275      1919.550 0.9018338       4726.680  1.9463181      1823.31
7   2.7872844      1919.550 1.1272922       4726.680  2.4328976      1823.31
8   3.3447412      1919.550 1.3527506       4726.680  2.9194771      1823.31
9   3.9021981      1919.550 1.5782091       4726.680  3.4060566      1823.31
10  4.4596550      1919.550 1.8036675       4726.680  3.8926361      1823.31
11  5.0171118      1919.550 2.0291260       4726.680  4.3792156      1823.31
12  5.5745687      1919.550 2.2545844       4726.680  4.8657952      1823.31
13  6.1320256      1919.550 2.4800428       4726.680  5.3523747      1823.31
14  6.6894824      1919.550 2.7055013       4726.680  5.8389542      1823.31
15  7.2469393      1919.550 2.9309597       4726.680  6.3255337      1823.31
16  7.8043962      1919.550 3.1564182       4726.680  6.8121132      1823.31
17  8.3618531      1919.550 3.3818766       4726.680  7.2986927      1823.31
18  8.9193099      1919.550 3.6073350       4726.680  7.7852722      1823.31
19  9.4767668      1919.550 3.8327935       4726.680  8.2718518      1823.31
20 10.0342237      1919.550 4.0582519       4726.680  8.7584313      1823.31
21 10.5916805      1919.550 4.2837103       4726.680  9.2450108      1823.31
22 11.1491374      1919.550 4.5091688       4726.680  9.7315903      1823.31
23 11.7065943      1919.550 4.7346272       4726.680 10.2181698      1823.31
24 12.2640512      1919.550 4.9600857       4726.680 10.7047493      1823.31
25 12.8215080      1919.550 5.1855441       4726.680 11.1913289      1823.31
26 13.3789649      1919.550 5.4110025       4726.680 11.6779084      1823.31
27 13.9364218      1919.550 5.6364610       4726.680 12.1644879      1823.31
28  0.0000000      1880.772 0.0000000       4694.691  0.0000000      1783.55
29  0.5539161      1880.772 0.2209038       4694.691  0.4832865      1783.55
30  1.1078322      1880.772 0.4418076       4694.691  0.9665729      1783.55
⋮  ⋮               ⋮        ⋮               ⋮        ⋮               ⋮
61  1.101380       1842.98  0.432930        4665.033  0.9604667      1744.602
62  1.652069       1842.98  0.649395        4665.033  1.4407001      1744.602
63  2.202759       1842.98  0.865860        4665.033  1.9209335      1744.602
64  2.753449       1842.98  1.082325        4665.033  2.4011669      1744.602
65  3.304139       1842.98  1.298790        4665.033  2.8814002      1744.602
66  3.854829       1842.98  1.515255        4665.033  3.3616336      1744.602
67  4.405518       1842.98  1.731720        4665.033  3.8418670      1744.602
68  4.956208       1842.98  1.948185        4665.033  4.3221003      1744.602
69  5.506898       1842.98  2.164650        4665.033  4.8023337      1744.602
70  6.057588       1842.98  2.381115        4665.033  5.2825671      1744.602
71  6.608278       1842.98  2.597580        4665.033  5.7628005      1744.602
72  7.158967       1842.98  2.814045        4665.033  6.2430338      1744.602
73  7.709657       1842.98  3.030510        4665.033  6.7232672      1744.602
74  8.260347       1842.98  3.246975        4665.033  7.2035006      1744.602
75  8.811037       1842.98  3.463440        4665.033  7.6837339      1744.602
76  9.361727       1842.98  3.679905        4665.033  8.1639673      1744.602
77  9.912416       1842.98  3.896370        4665.033  8.6442007      1744.602
78 10.463106       1842.98  4.112835        4665.033  9.1244341      1744.602
79 11.013796       1842.98  4.329300        4665.033  9.6046674      1744.602
80 11.564486       1842.98  4.545765        4665.033 10.0849008      1744.602
81 12.115176       1842.98  4.762230        4665.033 10.5651342      1744.602
82 12.665865       1842.98  4.978695        4665.033 11.0453675      1744.602
83 13.216555       1842.98  5.195160        4665.033 11.5256009      1744.602
84 13.767245       1842.98  5.411625        4665.033 12.0058343      1744.602
85 14.317935       1842.98  5.628090        4665.033 12.4860677      1744.602
86 14.868625       1842.98  5.844555        4665.033 12.9663010      1744.602
87 15.419314       1842.98  6.061020        4665.033 13.4465344      1744.602
88 15.970004       1842.98  6.277485        4665.033 13.9267678      1744.602
89 16.520694       1842.98  6.493950        4665.033 14.4070011      1744.602
90  0.000000       1805.05  0.000000        4635.280  0.0000000      1705.529
   Loan.D.Interest Loan.E   Loan.E.Interest
1  0.0000000       3359.170  0.0000000
2  0.0000000       3359.170  0.0000000
3  0.1876973       3359.170  0.4285758
4  0.3753947       3359.170  0.8571517
5  0.5630920       3359.170  1.2857275
6  0.7507894       3359.170  1.7143033
7  0.9384867       3359.170  2.1428792
8  1.1261841       3359.170  2.5714550
9  1.3138814       3359.170  3.0000308
10 1.5015788       3359.170  3.4286066
11 1.6892761       3359.170  3.8571825
12 1.8769735       3359.170  4.2857583
13 2.0646708       3359.170  4.7143341
14 2.2523682       3359.170  5.1429100
15 2.4400655       3359.170  5.5714858
16 2.6277629       3359.170  6.0000616
17 2.8154602       3359.170  6.4286375
18 3.0031576       3359.170  6.8572133
19 3.1908549       3359.170  7.2857891
20 3.3785522       3359.170  7.7143649
21 3.5662496       3359.170  8.1429408
22 3.7539469       3359.170  8.5715166
23 3.9416443       3359.170  9.0000924
24 4.1293416       3359.170  9.4286683
25 4.3170390       3359.170  9.8572441
26 4.5047363       3359.170 10.2858199
27 4.6924337       3359.170 10.7143958
28 0.0000000       3325.673  0.0000000
29 0.1836043       3325.673  0.4243022
30 0.3672087       3325.673  0.8486043
⋮  ⋮               ⋮        ⋮
61 0.3591898       3294.186  0.8405699
62 0.5387846       3294.186  1.2608549
63 0.7183795       3294.186  1.6811399
64 0.8979744       3294.186  2.1014248
65 1.0775693       3294.186  2.5217098
66 1.2571642       3294.186  2.9419948
67 1.4367590       3294.186  3.3622797
68 1.6163539       3294.186  3.7825647
69 1.7959488       3294.186  4.2028496
70 1.9755437       3294.186  4.6231346
71 2.1551386       3294.186  5.0434196
72 2.3347334       3294.186  5.4637045
73 2.5143283       3294.186  5.8839895
74 2.6939232       3294.186  6.3042745
75 2.8735181       3294.186  6.7245594
76 3.0531130       3294.186  7.1448444
77 3.2327079       3294.186  7.5651294
78 3.4123027       3294.186  7.9854143
79 3.5918976       3294.186  8.4056993
80 3.7714925       3294.186  8.8259843
81 3.9510874       3294.186  9.2462692
82 4.1306823       3294.186  9.6665542
83 4.3102771       3294.186 10.0868392
84 4.4898720       3294.186 10.5071241
85 4.6694669       3294.186 10.9274091
86 4.8490618       3294.186 11.3476940
87 5.0286567       3294.186 11.7679790
88 5.2082515       3294.186 12.1882640
89 5.3878464       3294.186 12.6085489
90 0.0000000       3262.575  0.0000000
   Memo
1
2
3  Food ;
4  Food ;
5  Food ;
6  Food ;
7  Phone + Internet ; Food ;
8  Food ;
9  Food ;
10 Food ;
11 Food ; Tank of Gas ;
12 Food ;
13 Food ; Income ;
14 Hulu ; Food ;
15 Food ;
16 Food ;
17 Food ;
18 Food ;
19 Food ;
20 Food ;
21 Food ;
22 Food ;
23 Food ;
24 Food ;
25 Food ;
26 Food ; Rent ;
27 Food ; Income ;
28 Loan C Min Pmt ; Loan A Min Pmt ; Loan D Min Pmt ; Food ; Loan E Min Pmt ; Loan B Min Pmt ;
29 Food ;
30 Food ;
⋮  ⋮
61 Food ;
62 Food ;
63 Minimum cc payment ; Food ;
64 Food ;
65 Food ;
66 Food ;
67 Food ;
68 Food ; Phone + Internet ;
69 Food ; Income ;
70 Food ;
71 Food ;
72 Tank of Gas ; Food ;
73 Food ;
74 Food ;
75 Hulu ; Food ;
76 Food ;
77 Food ;
78 Food ;
79 Food ;
80 Food ;
81 Food ;
82 Food ;
83 Food ;
84 Food ;
85 Food ;
86 Food ;
87 Food ;
88 Rent ; Food ;
89 Food ;
90 Loan D Min Pmt ; Loan C Min Pmt ; Food ; Loan B Min Pmt ; Loan A Min Pmt ; Loan E Min Pmt ;

In [93]:
data

   Date       Checking Savings Credit.1 Credit.1.Grace.Period.Balance Loan.A
1  2022-06-06  298.48  50      2434.88  1832.54                       4746.180
2  2022-06-07  258.48  50      4275.59    30.00                       4746.180
3  2022-06-08  258.48  50      4275.59    60.00                       4746.180
4  2022-06-09  258.48  50      4275.59    90.00                       4746.180
5  2022-06-10  258.48  50      4275.59   120.00                       4746.180
6  2022-06-11  258.48  50      4275.59   150.00                       4746.180
7  2022-06-12  258.48  50      4275.59   280.00                       4746.180
8  2022-06-13  258.48  50      4275.59   310.00                       4746.180
9  2022-06-14  258.48  50      4275.59   340.00                       4746.180
10 2022-06-15  258.48  50      4275.59   370.00                       4746.180
11 2022-06-16  258.48  50      4275.59   470.00                       4746.180
12 2022-06-17  258.48  50      4275.59   500.00                       4746.180
13 2022-06-18 2458.48  50      4275.59   530.00                       4746.180
14 2022-06-19 2458.48  50      4275.59   567.00                       4746.180
15 2022-06-20 2458.48  50      4275.59   597.00                       4746.180
16 2022-06-21 2458.48  50      4275.59   627.00                       4746.180
17 2022-06-22 2458.48  50      4275.59   657.00                       4746.180
18 2022-06-23 2458.48  50      4275.59   687.00                       4746.180
19 2022-06-24 2458.48  50      4275.59   717.00                       4746.180
20 2022-06-25 2458.48  50      4275.59   747.00                       4746.180
21 2022-06-26 2458.48  50      4275.59   777.00                       4746.180
22 2022-06-27 2458.48  50      4275.59   807.00                       4746.180
23 2022-06-28 2458.48  50      4275.59   837.00                       4746.180
24 2022-06-29 2458.48  50      4275.59   867.00                       4746.180
25 2022-06-30 2458.48  50      4275.59   897.00                       4746.180
26 2022-07-01  458.48  50      4275.59   927.00                       4746.180
27 2022-07-02 2658.48  50      4275.59   957.00                       4746.180
28 2022-07-03 2435.28  50      4275.59   987.00                       4716.591
29 2022-07-04 2435.28  50      4275.59  1017.00                       4716.591
30 2022-07-05 2435.28  50      4275.59  1047.00                       4716.591
⋮  ⋮          ⋮        ⋮       ⋮        ⋮                             ⋮
61 2022-08-05 4572.08  50      5427.175 1047                          4689.125
62 2022-08-06 4572.08  50      5427.175 1077                          4689.125
63 2022-08-07 4532.08  50      6571.543   30                          4689.125
64 2022-08-08 4532.08  50      6571.543   60                          4689.125
65 2022-08-09 4532.08  50      6571.543   90                          4689.125
66 2022-08-10 4532.08  50      6571.543  120                          4689.125
67 2022-08-11 4532.08  50      6571.543  150                          4689.125
68 2022-08-12 4532.08  50      6571.543  280                          4689.125
69 2022-08-13 6732.08  50      6571.543  310                          4689.125
70 2022-08-14 6732.08  50      6571.543  340                          4689.125
71 2022-08-15 6732.08  50      6571.543  370                          4689.125
72 2022-08-16 6732.08  50      6571.543  470                          4689.125
73 2022-08-17 6732.08  50      6571.543  500                          4689.125
74 2022-08-18 6732.08  50      6571.543  530                          4689.125
75 2022-08-19 6732.08  50      6571.543  567                          4689.125
76 2022-08-20 6732.08  50      6571.543  597                          4689.125
77 2022-08-21 6732.08  50      6571.543  627                          4689.125
78 2022-08-22 6732.08  50      6571.543  657                          4689.125
79 2022-08-23 6732.08  50      6571.543  687                          4689.125
80 2022-08-24 6732.08  50      6571.543  717                          4689.125
81 2022-08-25 6732.08  50      6571.543  747                          4689.125
82 2022-08-26 6732.08  50      6571.543  777                          4689.125
83 2022-08-27 6732.08  50      6571.543  807                          4689.125
84 2022-08-28 6732.08  50      6571.543  837                          4689.125
85 2022-08-29 6732.08  50      6571.543  867                          4689.125
86 2022-08-30 6732.08  50      6571.543  897                          4689.125
87 2022-08-31 6732.08  50      6571.543  927                          4689.125
88 2022-09-01 4732.08  50      6571.543  957                          4689.125
89 2022-09-02 4732.08  50      6571.543  987                          4689.125
90 2022-09-03 4508.88  50      6571.543 1017                          4661.558
   Loan.A.Interest Loan.B   Loan.B.Interest Loan.C   Loan.C.Interest Loan.D
1   0.0000000      1919.550 0.0000000       4726.680  0.0000000      1823.310
2   0.5574569      1919.550 0.2254584       4726.680  0.4865795      1823.310
3   1.1149137      1919.550 0.4509169       4726.680  0.9731590      1823.310
4   1.6723706      1919.550 0.6763753       4726.680  1.4597385      1823.310
5   2.2298275      1919.550 0.9018338       4726.680  1.9463181      1823.310
6   2.7872844      1919.550 1.1272922       4726.680  2.4328976      1823.310
7   3.3447412      1919.550 1.3527506       4726.680  2.9194771      1823.310
8   3.9021981      1919.550 1.5782091       4726.680  3.4060566      1823.310
9   4.4596550      1919.550 1.8036675       4726.680  3.8926361      1823.310
10  5.0171118      1919.550 2.0291260       4726.680  4.3792156      1823.310
11  5.5745687      1919.550 2.2545844       4726.680  4.8657952      1823.310
12  6.1320256      1919.550 2.4800428       4726.680  5.3523747      1823.310
13  6.6894824      1919.550 2.7055013       4726.680  5.8389542      1823.310
14  7.2469393      1919.550 2.9309597       4726.680  6.3255337      1823.310
15  7.8043962      1919.550 3.1564182       4726.680  6.8121132      1823.310
16  8.3618531      1919.550 3.3818766       4726.680  7.2986927      1823.310
17  8.9193099      1919.550 3.6073350       4726.680  7.7852722      1823.310
18  9.4767668      1919.550 3.8327935       4726.680  8.2718518      1823.310
19 10.0342237      1919.550 4.0582519       4726.680  8.7584313      1823.310
20 10.5916805      1919.550 4.2837103       4726.680  9.2450108      1823.310
21 11.1491374      1919.550 4.5091688       4726.680  9.7315903      1823.310
22 11.7065943      1919.550 4.7346272       4726.680 10.2181698      1823.310
23 12.2640512      1919.550 4.9600857       4726.680 10.7047493      1823.310
24 12.8215080      1919.550 5.1855441       4726.680 11.1913289      1823.310
25 13.3789649      1919.550 5.4110025       4726.680 11.6779084      1823.310
26 13.9364218      1919.550 5.6364610       4726.680 12.1644879      1823.310
27 14.4938786      1919.550 5.8619194       4726.680 12.6510674      1823.310
28  0.0000000      1880.997 0.0000000       4695.178  0.0000000      1783.738
29  0.5539816      1880.997 0.2209303       4695.178  0.4833366      1783.738
30  1.1079631      1880.997 0.4418606       4695.178  0.9666731      1783.738
⋮  ⋮               ⋮        ⋮               ⋮        ⋮               ⋮
61  1.101511       1843.206 0.4329831       4665.521  0.9605672      1744.790
62  1.652267       1843.206 0.6494747       4665.521  1.4408509      1744.790
63  2.203022       1843.206 0.8659663       4665.521  1.9211345      1744.790
64  2.753778       1843.206 1.0824579       4665.521  2.4014181      1744.790
65  3.304533       1843.206 1.2989494       4665.521  2.8817017      1744.790
66  3.855289       1843.206 1.5154410       4665.521  3.3619853      1744.790
67  4.406044       1843.206 1.7319326       4665.521  3.8422690      1744.790
68  4.956800       1843.206 1.9484241       4665.521  4.3225526      1744.790
69  5.507555       1843.206 2.1649157       4665.521  4.8028362      1744.790
70  6.058311       1843.206 2.3814073       4665.521  5.2831198      1744.790
71  6.609066       1843.206 2.5978989       4665.521  5.7634035      1744.790
72  7.159822       1843.206 2.8143904       4665.521  6.2436871      1744.790
73  7.710577       1843.206 3.0308820       4665.521  6.7239707      1744.790
74  8.261333       1843.206 3.2473736       4665.521  7.2042543      1744.790
75  8.812088       1843.206 3.4638652       4665.521  7.6845379      1744.790
76  9.362844       1843.206 3.6803567       4665.521  8.1648216      1744.790
77  9.913599       1843.206 3.8968483       4665.521  8.6451052      1744.790
78 10.464355       1843.206 4.1133399       4665.521  9.1253888      1744.790
79 11.015110       1843.206 4.3298314       4665.521  9.6056724      1744.790
80 11.565866       1843.206 4.5463230       4665.521 10.0859560      1744.790
81 12.116621       1843.206 4.7628146       4665.521 10.5662397      1744.790
82 12.667377       1843.206 4.9793062       4665.521 11.0465233      1744.790
83 13.218132       1843.206 5.1957977       4665.521 11.5268069      1744.790
84 13.768888       1843.206 5.4122893       4665.521 12.0070905      1744.790
85 14.319643       1843.206 5.6287809       4665.521 12.4873741      1744.790
86 14.870399       1843.206 5.8452724       4665.521 12.9676578      1744.790
87 15.421154       1843.206 6.0617640       4665.521 13.4479414      1744.790
88 15.971910       1843.206 6.2782556       4665.521 13.9282250      1744.790
89 16.522665       1843.206 6.4947472       4665.521 14.4085086      1744.790
90  0.000000       1805.277 0.0000000       4635.770  0.0000000      1705.718
   Loan.D.Interest Loan.E   Loan.E.Interest
1  0.0000000       3359.170  0.0000000
2  0.1876973       3359.170  0.4285758
3  0.3753947       3359.170  0.8571517
4  0.5630920       3359.170  1.2857275
5  0.7507894       3359.170  1.7143033
6  0.9384867       3359.170  2.1428792
7  1.1261841       3359.170  2.5714550
8  1.3138814       3359.170  3.0000308
9  1.5015788       3359.170  3.4286066
10 1.6892761       3359.170  3.8571825
11 1.8769735       3359.170  4.2857583
12 2.0646708       3359.170  4.7143341
13 2.2523682       3359.170  5.1429100
14 2.4400655       3359.170  5.5714858
15 2.6277629       3359.170  6.0000616
16 2.8154602       3359.170  6.4286375
17 3.0031576       3359.170  6.8572133
18 3.1908549       3359.170  7.2857891
19 3.3785522       3359.170  7.7143649
20 3.5662496       3359.170  8.1429408
21 3.7539469       3359.170  8.5715166
22 3.9416443       3359.170  9.0000924
23 4.1293416       3359.170  9.4286683
24 4.3170390       3359.170  9.8572441
25 4.5047363       3359.170 10.2858199
26 4.6924337       3359.170 10.7143958
27 4.8801310       3359.170 11.1429716
28 0.0000000       3326.102  0.0000000
29 0.1836237       3326.102  0.4243568
30 0.3672473       3326.102  0.8487137
⋮  ⋮               ⋮        ⋮
61 0.3592285       3294.617  0.8406797
62 0.5388428       3294.617  1.2610196
63 0.7184571       3294.617  1.6813594
64 0.8980713       3294.617  2.1016993
65 1.0776856       3294.617  2.5220392
66 1.2572999       3294.617  2.9423790
67 1.4369141       3294.617  3.3627189
68 1.6165284       3294.617  3.7830587
69 1.7961426       3294.617  4.2033986
70 1.9757569       3294.617  4.6237385
71 2.1553712       3294.617  5.0440783
72 2.3349854       3294.617  5.4644182
73 2.5145997       3294.617  5.8847580
74 2.6942140       3294.617  6.3050979
75 2.8738282       3294.617  6.7254378
76 3.0534425       3294.617  7.1457776
77 3.2330568       3294.617  7.5661175
78 3.4126710       3294.617  7.9864573
79 3.5922853       3294.617  8.4067972
80 3.7718996       3294.617  8.8271371
81 3.9515138       3294.617  9.2474769
82 4.1311281       3294.617  9.6678168
83 4.3107423       3294.617 10.0881566
84 4.4903566       3294.617 10.5084965
85 4.6699709       3294.617 10.9288364
86 4.8495851       3294.617 11.3491762
87 5.0291994       3294.617 11.7695161
88 5.2088137       3294.617 12.1898559
89 5.3884279       3294.617 12.6101958
90 0.0000000       3263.007  0.0000000
   Memo
1
2  Minimum cc payment ; Food ;
3  Food ;
4  Food ;
5  Food ;
6  Food ;
7  Phone + Internet ; Food ;
8  Food ;
9  Food ;
10 Food ;
11 Food ; Tank of Gas ;
12 Food ;
13 Food ; Income ;
14 Hulu ; Food ;
15 Food ;
16 Food ;
17 Food ;
18 Food ;
19 Food ;
20 Food ;
21 Food ;
22 Food ;
23 Food ;
24 Food ;
25 Food ;
26 Food ; Rent ;
27 Food ; Income ;
28 Loan C Min Pmt ; Loan A Min Pmt ; Loan D Min Pmt ; Food ; Loan E Min Pmt ; Loan B Min Pmt ;
29 Food ;
30 Food ;
⋮  ⋮
61 Food ;
62 Food ;
63 Minimum cc payment ; Food ;
64 Food ;
65 Food ;
66 Food ;
67 Food ;
68 Food ; Phone + Internet ;
69 Food ; Income ;
70 Food ;
71 Food ;
72 Tank of Gas ; Food ;
73 Food ;
74 Food ;
75 Hulu ; Food ;
76 Food ;
77 Food ;
78 Food ;
79 Food ;
80 Food ;
81 Food ;
82 Food ;
83 Food ;
84 Food ;
85 Food ;
86 Food ;
87 Food ;
88 Rent ; Food ;
89 Food ;
90 Loan D Min Pmt ; Loan C Min Pmt ; Food ; Loan B Min Pmt ; Loan A Min Pmt ; Loan E Min Pmt ;